services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algoraveshare-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: algoraveshare-adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
